# Generated by Django 3.0.1 on 2020-08-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotlistmodel',
            name='cost',
        ),
    ]
