# Generated by Django 3.0.1 on 2020-08-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_iotlistmodel_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IoTListModel',
        ),
    ]
