# Generated by Django 3.0.1 on 2020-08-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_delete_iotlistmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('abstract', models.TextField()),
                ('diagram', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
