# Generated by Django 3.0.1 on 2020-08-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_iotlistmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IoTListModel',
        ),
    ]
