# Generated by Django 3.0.1 on 2020-08-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200824_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotlistmodel',
            name='diagram',
        ),
    ]
