# Generated by Django 3.0.1 on 2020-08-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_iotlistmodel_diagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('phno', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
    ]
