# Generated by Django 3.0.1 on 2020-08-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200825_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmodel',
            name='Orderdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
