# Generated by Django 3.0.1 on 2020-08-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_checkoutmodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutmodel',
            name='phone',
        ),
        migrations.AlterField(
            model_name='checkoutmodel',
            name='phno',
            field=models.CharField(max_length=15),
        ),
    ]
