# Generated by Django 3.0.1 on 2020-08-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200825_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
