# Generated by Django 3.0.1 on 2020-08-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200825_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutmodel',
            name='date',
        ),
    ]
