# Generated by Django 3.0.1 on 2020-09-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_checkoutmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotlistmodel',
            name='diagram',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
